ranks:
- default
- member
- admin
port: 8273
server-ip: 
enable-webserver: true
config-version: 7
messages:
  issue: "&e[I:%id%] &b%target%&e, by &b%reporter%&e on &b%date%&e: %reason%"
  resolved-issue: "&e[I:%id%] &b&m%target%&e&m, by &b&m%reporter%&e&m on &b&m%date%&e&m: %reason%"
  promotion: "&a[P:%id%] &b%target%&a, by &b%reporter%&a, &b%oldrank%&a => &b%newrank%&a on &b%date%&a: %reason%"
  demotion: "&c[D:%id%] &b%target%&c, by &b%reporter%&c, &b%oldrank%&c => &b%newrank%&c on &b%date%&c: %reason%"
  ban: "&4[B:%id%] &b%target%&4, by &b%reporter%&4 on &b%date%&4: %reason%"
  unban: "&2[U:%id%] &b%target%&2, by &b%reporter%&2 on &b%date%&2: %reason%"
perform:
  issue:
  promote:
    - C:permissions player setgroup %target% %newrank%
  demote:
    - C:permissions player setgroup %target% %newrank%
  ban:
    - P:/ban %target% %reason%
  unban:
    - P:/unban %target%
accounts:
  admin: lolpassword
  moderator: icanhazpassword
  overlord: gimmecookies